use std::{env, fs, path::Path};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let plugin_dir = Path::new(&manifest_dir).join("src").join("plugin");

    // Re-run build.rs when the plugin directory structure changes.
    println!("cargo:rerun-if-changed={}", plugin_dir.display());

    // Scan for plugin sub-directories that contain mod.rs.
    let mut plugins: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&plugin_dir) {
        let mut entries: Vec<_> = entries.flatten().collect();
        entries.sort_by_key(|e| e.file_name()); // deterministic order
        for entry in entries {
            let path = entry.path();
            let mod_rs = path.join("mod.rs");
            if path.is_dir() && mod_rs.exists() {
                let name = path.file_name().unwrap().to_string_lossy().into_owned();
                // Escape backslashes for the generated Rust string literal.
                let abs_path = mod_rs.to_string_lossy().replace('\\', "\\\\");
                plugins.push((name, abs_path));
            }
        }
    }

    // Emit a cfg flag per detected plugin.
    // Use #[cfg(plugin_background)] etc. in source — no Cargo [features] needed.
    for (name, _) in &plugins {
        println!("cargo:rustc-cfg=plugin_{name}");
        // Register the cfg key to suppress unexpected_cfgs on Rust >= 1.80.
        println!("cargo:rustc-check-cfg=cfg(plugin_{name})");
    }

    // Generate plugin_mods.rs into OUT_DIR.
    // Uses #[path = "..."] so that the pub mod declaration resolves to the
    // real plugin directory (not OUT_DIR). plugin/mod.rs includes this file via:
    //   include!(concat!(env!("OUT_DIR"), "/plugin_mods.rs"));
    let out_dir = env::var("OUT_DIR").unwrap();
    let mut mods = String::from("// Auto-generated by build.rs — do not edit.\n");
    for (name, abs_path) in &plugins {
        mods.push_str(&format!(
            "#[cfg(plugin_{name})] #[path = \"{abs_path}\"] pub mod {name};\n"
        ));
    }
    fs::write(Path::new(&out_dir).join("plugin_mods.rs"), mods).unwrap();
}
