[package]
name = "quartz"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25.9", features = ["png"] }
prism  = { package = "prism2", path = "../prism"}
ramp  = { package = "ramp2", path = "../ramp"}
wgpu_canvas = {path="../wgpu_canvas", default-features = false}
crystalline = { path = "../crystalline" }
rodio = "0.21.1"
serde_json = "1.0.149"


